name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: "${{ matrix.version }}"
      - uses: actions/cache@v4
        with:
          key: deno-${{ hashFiles('**/*') }}
          restore-keys: deno-
          path: |
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Lint check
        run: deno lint
      - name: Format check
        run: deno fmt --check
      - name: Type check
        run: deno task check

  test:
    strategy:
      matrix:
        runner:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        version:
          - "1.38.x"
          - "1.x"
        host_version:
          - vim: "v9.0.2189"
            nvim: "v0.9.4"
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "vim-denops/denops.vim"
          path: ".deps/denops.vim"
      - uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: "${{ matrix.version }}"
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: "${{ matrix.host_version.vim }}"
      - name: Check Vim
        run: |
          echo ${DENOPS_TEST_VIM}
          ${DENOPS_TEST_VIM} --version
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable }}
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: "${{ matrix.host_version.nvim }}"
      - name: Check Neovim
        run: |
          echo ${DENOPS_TEST_NVIM}
          ${DENOPS_TEST_NVIM} --version
        env:
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable }}
      - name: Test
        run: deno task test:coverage
        env:
          DENOPS_TEST_DENOPS_PATH: ".deps/denops.vim"
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable }}
        timeout-minutes: 5
      - run: |
          deno task coverage --lcov > coverage.lcov
      - uses: codecov/codecov-action@v4
        with:
          os: ${{ runner.os }}
          files: ./coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
